export const menuItens = [
  {
    icone: "home",
    tooltip: "Início",
    label: "Início",
    rota: { name: "tarefas" },
  },
  {
    icone: "plus-square",
    tooltip: "Novo Protocolo",
    label: "Novo Protocolo",
    acao: "criarProtocolo",
    permissao: ["PROTOCOLO_CRIAR"],
  },
  {
    icone: "menu",
    tooltip: "Menu de Navegação",
    label: "Navegação",
    acao: "menuNavegacao",
  },
  {
    icone: "search",
    tooltip: "Buscar",
    label: "Buscar",
    rota: { name: "matricula.index" },
  },
  { separador: true, label: "Módulos" },
  {
    icone: "files",
    tooltip: "Protocolos",
    label: "Protocolos",
    rota: { name: "protocolo.lista" },
    permissao: ["PROTOCOLO_LISTAR"],
  },
  {
    icone: "file-pen-line",
    tooltip: "DOI",
    label: "DOI",
    rota: { name: "doi.index" },
    modulo: "DOI",
  },
  {
    icone: "folder",
    tooltip: "Contratos",
    label: "Contratos",
    rota: { name: "tarefas" },
    permissao: ["CONTRATO_LISTAR"],
  },
  {
    icone: "receipt",
    tooltip: "Recibos",
    label: "Recibos",
    rota: { name: "recibo.lista" },
    permissao: ["RECIBO_LISTAR"],
  },
  {
    icone: "calendar-days",
    tooltip: "Agenda",
    label: "Agenda",
    rota: { name: "tarefas" },
  },
  { separador: true, label: "Financeiro" },
  {
    icone: "store",
    tooltip: "Caixa",
    label: "Caixa",
    rota: { name: "caixa" },
    permissao: ["CAIXA_LISTAR"],
  },
  {
    icone: "landmark",
    tooltip: "Movimentos de Caixa",
    label: "Movimentos",
    rota: { name: "movimento-caixa" },
    permissao: ["CAIXA_MOVIMENTO_LISTAR"],
  },
  {
    icone: "arrow-right-left",
    tooltip: "Transações",
    label: "Transações",
    rota: { name: "transacao" },
    permissao: ["TRANSACAO_LISTAR"],
  },
  {
    icone: "tags",
    tooltip: "Categorias",
    label: "Categorias",
    rota: { name: "administracao.categoria" },
    permissao: ["CATEGORIA_LISTAR"],
  },
  {
    icone: "pie-chart",
    tooltip: "Relatórios",
    label: "Relatórios",
    rota: { name: "tarefas" },
  },
];
